### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by r3m4k3** [lchrusciel/Beery#84]
Hi there!

Great job!
I'm really impressed by your work, thank you also for giving us access to this resource.
Indeed, it's not an issue, but I have got one question and I don't know where to ask it, so I will try here.

To the point, I'm trying to understand the domain that you have presented us.
Why did you copy-pasted few times class Id, e.g. in class Beery/src/Domain/Beer/Model/Beer.php and appropriately Beery/src/Domain/Connoisseur/Model/Connoisseur.php? Is that because the Id of Beer context can be something different in the context of Connoisseur? 
It's replication and I'm pretty sure it's intentional, so I would like to know the reason for this procedure.

The second one - why only class Connoisseur has got a private constructor, and class Beer does not have it? I saw a pull request about it, but it does not include information, what was the cause - an omission or is it demand of Prooph framework or something different perhaps? 

Thank you, 
best regards!

**Comment by lchrusciel** [comment]
Hey Gregor,

It took me a while to answer you. At least we are still in the same year :D Thank you for the kind words.

**Disclaimer**: Code written here has some time, was created for educational purposes and not all of the decisions are optimal :)

I have created separate `Id` as they belong to different objects, so IDE will highlight the usage of the wrong class and I would have to be correct about choosen class. In the long term, it should make it easier to separate domains if needed. But having only one `id` could be a probably simpler solution without any trade-off at this stage. 

About the second question, missing private constructor is just missing clean up work. It didn't change too much about code itself. Should be unified with the Connoisseur.

I hope you found something useful for yourself here. 

Best regards!
